// Joke Generator - Main JavaScript File

let jokeCount = 0;
let currentJoke = '';

// API endpoints
const APIs = {
    jokesAPI: 'https://official-joke-api.appspot.com/random_joke',
    jokeAPIBase: 'https://v2.jokeapi.dev/joke',
};

// DOM Elements
const getJokeBtn = document.getElementById('getJokeBtn');
const shareBtn = document.getElementById('shareBtn');
const copyBtn = document.getElementById('copyBtn');
const jokeText = document.getElementById('jokeText');
const loading = document.getElementById('loading');
const notification = document.getElementById('notification');
const categorySelect = document.getElementById('category');
const jokeCountSpan = document.getElementById('jokeCount');

// Event Listeners
getJokeBtn.addEventListener('click', fetchJoke);
shareBtn.addEventListener('click', shareJoke);
copyBtn.addEventListener('click', copyJoke);

// Initialize
document.addEventListener('DOMContentLoaded', () => {
    loadJokeCount();
});

/**
 * Fetch a random joke from API
 */
async function fetchJoke() {
    const category = categorySelect.value;
    
    try {
        showLoading(true);
        
        let jokeData;
        
        if (category === 'any') {
            // Use Official Joke API for random jokes
            jokeData = await fetchFromOfficialAPI();
        } else {
            // Use JokeAPI for categorized jokes
            jokeData = await fetchFromJokeAPI(category);
        }
        
        if (jokeData) {
            displayJoke(jokeData);
            incrementJokeCount();
        }
        
        showLoading(false);
    } catch (error) {
        console.error('Error fetching joke:', error);
        showNotification('Failed to fetch joke. Please try again!', 'error');
        showLoading(false);
    }
}

/**
 * Fetch from Official Joke API
 */
async function fetchFromOfficialAPI() {
    try {
        const response = await fetch(APIs.jokesAPI);
        
        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }
        
        const data = await response.json();
        
        return {
            setup: data.setup,
            punchline: data.punchline
        };
    } catch (error) {
        console.error('Official API Error:', error);
        throw error;
    }
}

/**
 * Fetch from JokeAPI with category
 */
async function fetchFromJokeAPI(category) {
    try {
        const categoryMap = {
            'programming': 'Programming',
            'knock-knock': 'Knock-knock',
            'general': 'General',
            'spooky': 'Spooky'
        };
        
        const categoryValue = categoryMap[category] || 'Any';
        const url = `${APIs.jokeAPIBase}/${categoryValue}`;
        
        const response = await fetch(url);
        
        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }
        
        const data = await response.json();
        
        // Handle JokeAPI response
        if (data.error) {
            // If no jokes in category, fallback to random
            return await fetchFromOfficialAPI();
        }
        
        return {
            setup: data.setup || data.joke,
            punchline: data.delivery || ''
        };
    } catch (error) {
        console.error('JokeAPI Error:', error);
        // Fallback to official API
        return await fetchFromOfficialAPI();
    }
}

/**
 * Display the joke
 */
function displayJoke(jokeData) {
    if (jokeData.punchline) {
        // Two-part joke
        currentJoke = `${jokeData.setup}\n\n${jokeData.punchline}`;
        jokeText.textContent = currentJoke;
    } else {
        // Single-part joke
        currentJoke = jokeData.setup || jokeData.joke;
        jokeText.textContent = currentJoke;
    }
    
    jokeText.style.animation = 'none';
    setTimeout(() => {
        jokeText.style.animation = 'slideIn 0.5s ease-out';
    }, 10);
}

/**
 * Share joke on social media
 */
function shareJoke() {
    if (!currentJoke) {
        showNotification('No joke to share! Get a joke first.', 'error');
        return;
    }
    
    const text = encodeURIComponent(currentJoke + '\n\n😂 Generated by Joke Generator');
    const url = window.location.href;
    
    const shareOptions = {
        'twitter': `https://twitter.com/intent/tweet?text=${text}&url=${encodeURIComponent(url)}`,
        'facebook': `https://www.facebook.com/sharer/sharer.php?quote=${text}&href=${encodeURIComponent(url)}`,
        'whatsapp': `https://wa.me/?text=${text}`,
        'linkedin': `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`
    };
    
    // Create share dialog
    const platform = prompt('Share on:\n1. Twitter\n2. Facebook\n3. WhatsApp\n4. LinkedIn\n5. Copy Link\n\nEnter number (1-5):');
    
    switch(platform) {
        case '1':
            window.open(shareOptions.twitter, '_blank', 'width=600,height=400');
            showNotification('Opening Twitter...', 'success');
            break;
        case '2':
            window.open(shareOptions.facebook, '_blank', 'width=600,height=400');
            showNotification('Opening Facebook...', 'success');
            break;
        case '3':
            window.open(shareOptions.whatsapp, '_blank');
            showNotification('Opening WhatsApp...', 'success');
            break;
        case '4':
            window.open(shareOptions.linkedin, '_blank');
            showNotification('Opening LinkedIn...', 'success');
            break;
        case '5':
            copyToClipboard(currentJoke + '\n\n' + url);
            showNotification('Share link copied!', 'success');
            break;
        default:
            if (platform !== null) {
                showNotification('Invalid option', 'error');
            }
    }
}

/**
 * Copy joke to clipboard
 */
function copyJoke() {
    if (!currentJoke) {
        showNotification('No joke to copy!', 'error');
        return;
    }
    
    copyToClipboard(currentJoke);
    showNotification('Joke copied to clipboard!', 'success');
}

/**
 * Copy text to clipboard (helper function)
 */
function copyToClipboard(text) {
    if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(text);
    } else {
        // Fallback for older browsers
        const textarea = document.createElement('textarea');
        textarea.value = text;
        document.body.appendChild(textarea);
        textarea.select();
        document.execCommand('copy');
        document.body.removeChild(textarea);
    }
}

/**
 * Show/hide loading spinner
 */
function showLoading(show) {
    loading.style.display = show ? 'block' : 'none';
    getJokeBtn.disabled = show;
}

/**
 * Show notification message
 */
function showNotification(message, type = 'info') {
    notification.textContent = message;
    notification.className = `notification ${type} show`;
    
    setTimeout(() => {
        notification.classList.remove('show');
    }, 3000);
}

/**
 * Increment and save joke count
 */
function incrementJokeCount() {
    jokeCount++;
    jokeCountSpan.textContent = jokeCount;
    localStorage.setItem('jokeCount', jokeCount);
}

/**
 * Load joke count from localStorage
 */
function loadJokeCount() {
    const saved = localStorage.getItem('jokeCount');
    if (saved) {
        jokeCount = parseInt(saved);
        jokeCountSpan.textContent = jokeCount;
    }
}

// Keyboard shortcut: Press 'Enter' to get a joke
document.addEventListener('keydown', (e) => {
    if (e.key === 'Enter' && document.activeElement !== categorySelect) {
        fetchJoke();
    }
});
